### PR TITLE
Add icons to investor list table

### PR DESCRIPTION
**Pull request by kattylucy**
### Description

Adds network icon to the investor list table

#2243 

### Approvals

- [x ] Dev
- [ ] Dev
- [ ] Designer
- [ ] Product

### Screenshots
Screenshot 2024-06-26 at 11 01 19 AM

### CODE REVIEW

**Comment by kattylucy** [comment]
It seems like we don't use the column anymore, but let me know if Im wrong and how to locate it! 

Thank you! @hieronx 

_Also, could you make the same change to the Network column in the Investor transactions report?_

**Comment by hieronx** [comment]
Screenshot 2024-06-26 at 18 45 51

@kattylucy I'm referring to this column here

**Comment by kattylucy** [comment]
Ahhhhh! Thanks! @hieronx

**Comment by kattylucy** [comment]
Changes added:

* Icon on investor transactions network
* Change centrifuge to Centrifuge

Screenshot 2024-06-26 at 11 50 59 AM

**Comment by hieronx** [comment]
Screenshot 2024-06-26 at 19 40 38

Something strange happened here, the Account table now contains the network name and the other values got moved up as well

**Comment by kattylucy** [comment]
Sorry for overseeing this - I added a new line without deleting the told column. Should be good now

Screenshot 2024-06-26 at 1 15 53 PM

**Comment by hieronx** [comment]
Will test again in a bit!

> Just a bit of a question. I realized that the network filter dropdown does not have Ethereum and if I click "base" (assuming base is ethereum) it shows nothing, this is happening on main branch . Is this how is intended to work?

Not showing anything on Base makes sense since there are no investors there yet. But not having Ethereum is a bug. If you can figure out why, would be great if you can fix it, but we can also create a ticket to tackle it later!

**Review by hieronx — APPROVED** [review]
Just retested, works perfectly! 🔥

**Comment by kattylucy** [comment]
> Just retested, works perfectly! 🔥



> Just retested, works perfectly! 🔥

Great! Thanks, I will look into the ethereum issue tomorrow and see if I can find a fix for it to add to the PR!

**Pull request merged**
