### PR TITLE
Port gateway to 2.0

### PR DESCRIPTION
**Pull request by avinashega**
### Description

This pull request migrates the gateway to use 2,0 endpoints

Closes #<issue-number>

### Approvals

- [ ] Dev
- [ ] Dev

### CODE REVIEW

**Comment by mikiquantum** [comment]
@avinashega @offerijns @jpangelle What is left to get this in? So I can deploy this new version in Catalyst to verify E2E flow

**Comment by mikiquantum** [comment]
In addition, would these code changes be backwards compatible with the current database state? Meaning, for existing user data and not only new documents.

**Comment by offerijns** [comment]
> @avinashega @offerijns @jpangelle What is left to get this in? So I can deploy this new version in Catalyst to verify E2E flow

Avi is off this week and JP hasn't been involved, but from what I know, it's already been tested against node v2 on amber. It just needs to be deployed and tested in Catalyst now. And from what I've understood, the changes should all be backwards compatible, yes. Although looking at the changes now, I find it hard to say that with any certainty. I'll check with Avi on Monday.

**Comment by mikiquantum** [comment]
ok, I can try building locally and pushing a temp docker image and use it in catalyst for now and see how it goes. I would like to test the whole flow out tomorrow/monday max.

**Review by mikiquantum — APPROVED** [review]
LGTM!

**Pull request merged**
