### PR TITLE
Utilize on chain data for token price pool graph

### PR DESCRIPTION
**Pull request by kattylucy**
### Description

- Utilize on chain data for token price & nav 
- Keep only months on graph regarding data length to maintain consistency 
- Show only one month per internal, do not repeat month or skip months

#2312 
#2310 

### Approvals

- [ ] Dev

### CODE REVIEW

**Review by sophialittlejohn — COMMENTED** [review]
there still seems to be a discrepancy between the token prices displayed - I'm seeing three different token prices on the page (above the chart, in the chart tooltip for today, underneath the chart in the blue box).I think it would help to replace the last day of the subquery data in the chart with chain data from today?

**Comment by kattylucy** [comment]
Hmmm that's weird. I will double check. It seems we want to move away from the subquery for this one.

Thank you for checking!! @sophialittlejohn

**Review by sophialittlejohn — COMMENTED** [review]
I would suggest a slightly different approach:
```js
  const todayPrice = pool?.tranches[pool.tranches.length - 1].tokenPrice?.toDecimal().toNumber() || null
  const todayNav = pool.nav.total.toDecimal().toNumber()

  const isSingleTranche = pool?.tranches.length === 1
  const data: ChartData[] = React.useMemo(
    () =>
      truncatedPoolStates?.map((day) => {
        const nav = day.poolState.netAssetValue.toDecimal().toNumber()
        const price = (isSingleTranche && Object.values(day.tranches)[0].price?.toFloat()) || null
        // Replace the data as it's being created for the chart so that data stays consistent with the UI
        if (day.timestamp && new Date(day.timestamp).toDateString() === new Date().toDateString()) {
          return { day: new Date(day.timestamp), nav: todayNav, price: todayPrice }
        }
        return { day: new Date(day.timestamp), nav, price }
      }) || [],
    [isSingleTranche, truncatedPoolStates]
  )
```

**Review by sophialittlejohn — APPROVED** [review]
🥳

**Pull request merged**
