### PR TITLE
fix: change pool id in subgraph query to be lowercase

### PR DESCRIPTION
**Pull request by philipstanislaus**

### CODE REVIEW

**Comment by philipstanislaus** [comment]
Mainnet preview: https://606d5918957fb997acca592a--tinlake-mainnet-production.netlify.app/

**Comment by philipstanislaus** [comment]
Updated preview: https://606f05a6ff6120e1083a2a9d--tinlake-mainnet-production.netlify.app/

**Comment by philipstanislaus** [comment]
Updated preview: Our team consist of me, Jan, and Philip. I have started organizing events with x people... . Together with my financial background and a deep passion for the music space.

Hi, I'm Philip, CTO of Syngular. I have spent the last years in the blockchain space, building the technology for THORChain (having a $2.5B valuation as of today). I have hired more than 50 people over that time, and have a strong experience

**Comment by philipstanislaus** [comment]
Updated preview: https://60746ad27b914e48120f46b0--tinlake-mainnet-production.netlify.app/

**Review by offerijns — APPROVED** [review]

**Pull request merged**
