### PR TITLE
RWA dashboard

### PR DESCRIPTION
**Pull request by alessioscalici**
### Description

This pull request:
- applies design changes to the main Tinlake page (Pool list) moving the RWA block outside of the pool list, on top.
- adds a new RWA Dashboard page.
- changes the behaviour of the RWA block in the Pool list page: instead of opening the [rwamarket.io](https://rwamarket.io/) page in a new tab, it opens the RWA Dashboard page in the same tab.
- adds the necessary methods and configuration to `tinlake-js`

Closes [#685](https://github.com/centrifuge/apps/issues/685)

### Approvals

- [ ] Dev
- [ ] Dev
- [ ] Designer
- [ ] Product

#### Pool list: debug flag OFF
Screenshot 2022-04-29 at 08 45 11

#### Pool list: debug flag ON
Screenshot 2022-04-29 at 08 48 06

#### RWA Dashboard top
localhost_3000_ (3)

#### RWA Dashboard bottom
Screenshot 2022-04-29 at 09 00 15

### Impact

No Impact (under debug flag)

### CODE REVIEW

**Comment by armandomistral** [comment]
Could we apply the same mechanism to showing the welcome message as on the dashboard? I.e. showing the message including the CTA `Onboard as investor` only if not connected OR not onboarded.
image

**Comment by EstherCentrifuge** [comment]
this is now deployed it seems can we close it? @armandomistral @denniswell

**Comment by EstherCentrifuge** [comment]
this is now deployed it seems can we close it? @armandomistral @denniswell

**Comment by armandomistral** [comment]
@EstherCentrifuge, it's not live on https://tinlake.centrifuge.io/ yet. It looks like there's still a review needed from Jeroen and Onno...

**Comment by EstherCentrifuge** [comment]
Neuh they decided to close it 70% finished: https://centrifugehq.slack.com/archives/C033T5YUX0W/p1655458338222269

**Pull request closed without merging**
