### PR TITLE
add upcoming pools

### LINKED ISSUE #1582: Add Upcoming pools to Centrifuge app
### Pools

[Figma Design](https://www.figma.com/file/9iwvzHuvbjlHXRWlPWRxxc/Centrifuge-app---Version-2-(Branch)?type=design&node-id=13663-21785&mode=design&t=PkS1G3SKtLAGcsFw-0)

```
New Silver Series 3
Real Estate Bridge Loans
Target: 8%
Coming soon

Flowcarbon Nature Offsets Series 2
Voluntary Carbon Offsets
Target: 15%
Coming soon

```

Screenshot 2023-09-14 at 18 42 46

### PR DESCRIPTION
**Pull request by jpangelle**
### Description

This pull request adds the two upcoming pools, New Silver Series 3 and Flowcarbon Nature Offsets Series 2.

Closes #1582 

### Approvals

- [x] Dev
- [x] Product

### Screenshots

image

### CODE REVIEW

**Comment by annamehr** [comment]
@jpangelle looks good! Small request can you display the upcoming pools at the beginning of the list instead of at the end? Then we show the new cool pools at the top.

**Comment by jpangelle** [comment]
> @jpangelle looks good! Small request can you display the upcoming pools at the beginning of the list instead of at the end? Then we show the new cool pools at the top.

done!

**Comment by sophialittlejohn** [comment]
The APR column looks like it should be aligned to the right side. Maybe by putting `Target` on the right side of the APR rather than the left it would look aligned again? Typically numbers are always right aligned in our tables

**Review by sophialittlejohn — APPROVED** [review]
🥳

**Pull request merged**
