### PR TITLE
feat(tinlake-ui): display ENS avatar

### LINKED ISSUE #574: Add ENS avatar support
Screenshot 2022-01-05 at 5 06 01 PM

### PR DESCRIPTION
**Pull request by bigint**
### Description

Show ENS avatar if user has it

Closes #574

### Approvals

- [x] Dev
- [x] Dev
- [x] Designer
- [x] Product

### Screenshots

image

### CODE REVIEW

**Comment by bigint** [comment]
cc @offerijns

**Review by onnovisser — APPROVED** [review]
Nice, LGTM!

**Comment by bigint** [comment]
Great thanks for the review @onnovisser 🤗

**Comment by bigint** [comment]
@onnovisser any ideas why CI got failed?

**Review by jpangelle — APPROVED** [review]
👍

**Comment by jpangelle** [comment]
> @onnovisser any ideas why CI got failed?

hey @bigint!

Thanks for contributing. It looks like the CI job is failing because Github secrets are not password to forks and since the build relies on a particular secret being available, it is failing. I'm looking into it.

**Comment by jpangelle** [comment]
> > @onnovisser any ideas why CI got failed?
> 
> hey @bigint!
> 
> Thanks for contributing. It looks like the CI job is failing because Github secrets are not password to forks and since the build relies on a particular secret being available, it is failing. I'm looking into it.

I just went ahead and merged it since the pr scope was small and it was clear why the CI job is failing. The ci job on `main` is passing now! Thanks again! 🎉

**Pull request merged**
